flyway:
  locations:
    - db/migration/mysql
    
# Database settings.
datasource:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: p$ssw0rd
  url: jdbc:mysql://${DB_HOST:-localhost}:${DB_PORT:-3306}/my_app_db?useUnicode=true&characterEncoding=UTF-8&useLocalSessionState=true&useSSL=false&allowPublicKeyRetrieval=true
  
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081